### PR TITLE
Added FRENCH translation

### PR DESCRIPTION
**Pull request by dumasflo**
I just have 2 sentences I need explanations for :

- Autorebuild is on for a new game
- Dropdown designators get their order set by their contained designators

I just don't really understand what those means, if you could explain what it does so I can find the right translation for it.

Otherwise I tested the rest of it and looks cool to me.

### CODE REVIEW

**Comment by alextd** [comment]
Yeah,

#1 That's the "Auto-rebuild a building after it's destroyed" option, toggleable icon on the bottom-right.


#2 'Designator' just means any tool button where you use your mouse to target, like mining rock or placing buildings. So 'Dropdown designators' basically means that button uses a dropdown list, like how colored lights has you choose the color.

The normal game is confused where to put colored lights in the menu, since the button for colored lights uses a dropdown list ("Dropdown designators"), which isn't the same as the other building designators. It was a simple fix to use the ordering of the colored lights inside the dropdown list ( the "contained designators") to determine where the button for colored lights should go in the menu.

The simple meaning is in the next line : <TD.DropdownBuildingsOrderDesc>e.g. colored lights show up in the build menu next to other lights instead of the front of the list</TD.DropdownBuildingsOrderDesc>

**Comment by dumasflo** [comment]
Ok ! I finally understand what both mean, I updated the translation.

**Comment by alextd** [comment]
Hey, I was dumb and didn't make all strings translatable so there are a few more things to translate - check out the added strings in latest commits

( and after this I'll just take new pull requests whenever )

**Comment by dumasflo** [comment]
Hey, ok I'll do that !

**Comment by alextd** [comment]
specifically : 
<TD.PasteFrom>Paste from</TD.PasteFrom>
<TD.SettingsZoomToMouse>Zoom to Mouse</TD.SettingsZoomToMouse>
<TD.AlertBurning>A colonist is burning, and is rapidly gaining heatstroke.</TD.AlertBurning>
<TD.AlertHeatstrike>A colonist is gaining heatstroke. Thats not a good thing.</TD.AlertHeatstrike>
<TD.AlertToxic>A colonist has non-trivial levels of toxic buildup. Thats not a good thing.</TD.AlertToxic>

**Pull request merged**
